### ISSUE TITLE
Test is not marked as xfailed

### ISSUE THREAD

**Issue by MaxoH4uk** [okken/pytest-check#134]
Hello!

When i call the method `pytest.xfail()` the test is marked as XFAIL:

    def test_foo():
        pytest.xfail()

![image](https://github.com/okken/pytest-check/assets/16401952/bdf628d7-93c1-4f56-b23a-ec5bc114d237)

But if before calling the method `pytest.xfail()` any of the methods pytest_check returns false, then the test is marked as failed:

    def test_foo():
        pytest_check.is_true(1 == 2, 'qwerty')
        pytest.xfail()

![image](https://github.com/okken/pytest-check/assets/16401952/17489b62-a33d-4aff-b24a-5081416d5dc6)

**Comment by okken** [comment]
Yep. That will happen if using the standard `pytest.xfail()` function.  
The reason is that the implementation of `pytest.xfail()` is to raise an exception. [See implementation](https://github.com/pytest-dev/pytest/blob/556e075d23a91eb42821129a5d874ec3174e17ad/src/_pytest/outcomes.py#L231).
The `xfail()` function doesn't just mark the test as xfail, it raises an exception and stops the test.

The workarounds are.
1. Use the `@pytest.mark.xfail` decorator on the function if you know the test function is always xfail.
2. If you need some collection time logic to determine xfail-ness, use the condition parameter to `@pytest.mark.xfail()`.
3. If you need to determine xfail-ness at test runtime, then try using the pytest-runtime-xfail plugin and the `runtime_xfail` fixture. You still may need to call the function before the `check.is_true()` is called, but honestly I don't remember.

I hope this helps.
