### ISSUE TITLE
pytest_html

### ISSUE THREAD

**Issue by erlebach** [okken/pytest-check#148]
When running pytest_check I have two issues. First, the code: 
```
import pytest
from pytest_check import check

def test_example():
    a = 1
    b = 2
    c = [2, 4, 6]
    check.greater(a, b)
    d = a
    check.less_equal(b, a)
    check.equal(a, d, "a == d, should pass")    #### SHOULD PASS
    check.is_not_in(b, c, "make sure 2 isn't in list")
```
produces the output: 
```
FAILURE: check 1 > 2
test_example.py:8 in test_example() -> check.greater(a, b)

FAILURE: check 2 <= 1
FAILURE: check 2 not in [2, 4, 6]: make sure 2 isn't in list
------------------------------------------------------------
Failed Checks: 3
================================================================================================ short test summary info ================================================================================================
FAILED tests/test_example.py::test_example
=================================================================================================== 1 failed in 0.02s ===================================================================================================
```
There is listing of the test that passed, and it is not among the listed failed tests. 

Second, when used with `pytest_html`, the HTML produced ignores that output of `pytest_check` and lists one failed test and zero tests passed. 

Has anybody worked with the combination of pytest_check and pytest_html? Thanks!

    Gordon

**Comment by okken** [comment]
This seems to work as designed for me.
* There is one test, which fails due to three failed checks.
* There are no passing tests. There's just the one test.
* The output for the failed checks is included in the html report for the failed test.

Perhaps there's some confusion about checks. They don't create extra "tests", they just are multiple opportunities to fail a test.

<img width="938" alt="Screenshot 2023-12-21 at 3 17 15 PM" src="https://github.com/okken/pytest-check/assets/1568356/08dbd4d2-07e2-4d2b-ad87-9f326e04fb76">
